### PR TITLE
Update german translations resw file

### PR DESCRIPTION
**Pull request by chingucoding**
Restore german translations for the German resw file. This fixes that selecting German did not actually provide German text in Quick Pad but rather Portuguese.

### CODE REVIEW

**Review by yaichenbaum — APPROVED** [review]
LGTM

**Comment by yaichenbaum** [comment]
@chingucoding It looks like we needed to edit the xliff file instead of the resw file.

**Comment by chingucoding** [comment]
I'll take a look when I have time @yaichenbaum !

**Comment by yaichenbaum** [comment]
Thanks!

**Comment by chingucoding** [comment]
@yaichenbaum The `QuickPad.UI.de.xlf` already seems to be correctly translated, all entries are German translations.

**Comment by yaichenbaum** [comment]
I'll look into it, thanks!

**Comment by yaichenbaum** [comment]
@chingucoding I was able to sovle the issue. It turnes out the files had the wrong name and ID set.

**Comment by chingucoding** [comment]
Ohhhh I see, glad that we know what the issue was :)

**Comment by yaichenbaum** [comment]
@SirKubiac the update is rolling out now, can you confirm if the issue is resolved?

**Comment by SirKubiac** [comment]
Problem is resolved. Everything is now in German. Perfect. 👍

**Pull request merged**
