### PR TITLE
fix multiline tabbing, add untab

### PR DESCRIPTION
**Pull request by johnwang16**
Fixes bug where selecting multiple lines and pressing tab causes the selection to shrink. Allows removal of tabs using shift-tab.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@johnwang16 can you confirm that this works with rich text files as well as regular text files?

**Comment by johnwang16** [comment]
oh.. good catch. I'll fix it for rtfs. Are there other odd formats that I should be aware of?

**Comment by yaichenbaum** [comment]
> oh.. good catch. I'll fix it for rtfs. Are there other odd formats that I should be aware of?

Just rtf and txt

**Comment by johnwang16** [comment]
After some digging, there's an issue with RTFs that's not related to this PR. It exists in the current codebase here https://github.com/yaichenbaum/Quick-Pad/blob/2b11ef0dc77dacaa29ec375f9d5599e89c379fa5/src/QuickPad.Standard.Mvvm/ViewModels/DocumentViewModel.cs#L262
Text.Substring returns a cut of the raw RTF file, which contains all of the extra formatting markup and throws off the character offsets.

**Comment by yaichenbaum** [comment]
@johnwang16 I don't have an issue merging this as is but it would be nice if the behavior was consistent.

**Comment by johnwang16** [comment]
Yes, I agree. I might have something that will at least partially fix rtf tabs. I'll investigate more this week.

**Comment by johnwang16** [comment]
should be fixed for rtf files now

**Comment by yaichenbaum** [comment]
@johnwang16 I just tested the changes and it shift + tab doesn't seem to work for txt files.

**Comment by johnwang16** [comment]
The current implementation only removes tabs if it is part of the selection. Looking over Notepads source, they use GetRect to expand that selection
image

**Comment by yaichenbaum** [comment]
> The current implementation only removes tabs if it is part of the selection. Looking over Notepads source, they use GetRect to expand that selection image

Would it be possible to match the behavior of Visual Studio?

**Comment by yaichenbaum** [comment]
Closing due to inactivity (would love to merge this if the issues are addressed).

**Comment by Shawnblake** [comment]
****

**Pull request closed without merging**
